networks:
    pollux:

services:
    #pollux_framework:
    #    image: ghcr.io/pollux-digital-twin/pollux-framework:latest
    #    environment:
    #        - POLLUX_PLANT=   # put project name
    #        - INFLUXDB_URL=http://influxdb:8086
    #        - INFLUXDB_ORG=TNO
    #        - INFLUXDB_USERNAME=pollux-username
    #        - INFLUXDB_PASSWORD=pollux-password
    #        - INFLUXDB_BUCKET=pollux-project
    #    volumes:
    #        - project-db:/opt/pollux-project
    #    depends_on:
    #        - influxdb
    #    networks:
    #        - pollux
    #
    #pollux_gui:
    #    image: ghcr.io/pollux-digital-twin/pollux-user-interface:latest
    #    ports:
    #        - 5101:5101
    #    environment:
    #        - POLLUX_FRONTEND_PORT=5101
    #        - POLLUX_MYSQLDB_URL=mysqldb
    #        - CELERY_BROKER_URL=redis://redis:6379/0
    #        - CELERY_RESULT_BACKEND=redis://redis:6379/0
    #        - MONGODB_HOST=mongodb
    #        - MONGODB_PORT=27017
    #        - MONGODB_USERNAME=root
    #        - MONGODB_USERNAME=pollux
    #        - INFLUXDB_URL=http://influxdb:8086
    #        - INFLUXDB_ORG=TNO
    #        - INFLUXDB_USERNAME=pollux-username
    #        - INFLUXDB_PASSWORD=pollux-password
    #        - INFLUXDB_BUCKET=pollux-project
    #        - POLLUX_ADMIN_EMAIL=admin@localhost
    #        - POLLUX_ADMIN_PASSWORD=Admin123456!@#$
    #    restart: unless-stopped
    #    volumes:
    #        - project-db:/opt/pollux-project
    #        - doc-db:/opt/pollux-documentation
    #    depends_on:
    #        - mysqldb
    #        - influxdb
    #        - mongodb
    #    networks:
    #        - pollux
    #
    #pollux_doc:
    #    image: ghcr.io/pollux-digital-twin/pollux-documentation:latest
    #    restart: unless-stopped
    #    volumes:
    #        - doc-db:/opt/pollux-documentation
    #    networks:
    #        - pollux

    pollux_project:
        image: ghcr.io/pollux-digital-twin/pollux-project:latest
        restart: unless-stopped
        volumes:
            - project-db:/opt/pollux-project
        networks:
            - pollux

    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING=true
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=P0lluX_@dmin
        volumes:
            - grafana-storage:/var/lib/grafana
        depends_on:
            - influxdb
        networks:
            - pollux

    mysqldb:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=polluxdb
        volumes:
            - mysqldb_data-storage:/data/db
            - mysqldb_var_lib-storage:/var/lib/mysql
        restart: unless-stopped
        networks:
            - pollux

    influxdb:
        image: influxdb:latest
        ports:
            - 8086:8086
            - 8998:8088
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_ORG=TNO
            - DOCKER_INFLUXDB_INIT_BUCKET=pollux-project
            - DOCKER_INFLUXDB_INIT_USERNAME=pollux-user
            - DOCKER_INFLUXDB_INIT_PASSWORD=pollux-password
        volumes:
            - influxdb-storage:/var/lib/influxdb
            - influxdb2-storage:/var/lib/influxdb2
            - influxdb2etc-storage:/etc/influxdb2
        restart: unless-stopped
        networks:
            - pollux

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pollux
        volumes:
            - mongo-storage:/data/db
        restart: unless-stopped
        networks:
            - pollux

volumes:
    mysqldb_data-storage:
    mysqldb_var_lib-storage:
    grafana-storage:
    influxdb-storage:
    influxdb2-storage:
    influxdb2etc-storage:
    project-db:
    doc-db:
    mongo-storage:
